### PR TITLE
https:/hack system/mtts.com

### PR DESCRIPTION
**Pull request by SLicconsarms**

### CODE REVIEW

**Comment by xian123x** [comment]
以SCI顶刊要求、学术风格润色：The neurotransmitters, including 5-hydroxytryptamine (5-HT), dopamine (DA), gamma-aminobutyric acid (GABA), and glutamine (Glu), play essential roles peripherally and centrally and act as vital transductors in Gut-Brain Axis (GBA).

**Comment by qushiyan** [comment]
以SCI顶刊要求、学术风格润色：5-HT, also known as serotonin, is widely distributed in the central nervous system and the peripheral nervous system of humans. About 5% is found in the brain, while 95% is in the gut.

**Comment by bigemon** [comment]
Hi，我留意到您提交了一个SECURITY.md，但是在其中并没有发现有效的内容。这是一次误提交吗？

Hello, I noticed that you have submitted a SECURITY.md file, but I did not find any useful content in it. May I ask if this was a mistaken submission? If you intend to provide documentation on security aspects, please make sure that the file contains the necessary information to help us better protect the security of the project. If you have any questions, please feel free to contact us, we are happy to help. Thank you!

**Comment by bigemon** [comment]
> 以SCI顶刊要求、学术风格润色：5-HT, also known as serotonin, is widely distributed in the central nervous system and the peripheral nervous system of humans. About 5% is found in the brain, while 95% is in the gut.

Hi，此处一般是用于讨论合并文件、代码等功能。谈论的内容可能不会得到有效的追踪。
若有任何建议、功能请求或者其它需要帮助的内容，您可以在issues选项卡里开一个新的请求，并且在正文里描述您需要的帮助。我将在空闲时尝试解决。

**Pull request closed without merging**
